var fname = "Akbar";
var lname = "Ali";
var str = "I love typescript";
console.log(fname.concat(lname));
console.log(str.split(' '));
console.log(str.split(' ', 2));
console.log(fname.toUpperCase());
console.log(lname.toLowerCase());
console.log(str.substring(0, 5));
console.log(fname.charAt(2));
var a = 10;
var b = 7;
var c = 12;
var max = Math.max(a, b, c);
var min = Math.min(a, b, c);
var mid = (a + b + c) - (max + min);
console.log(min, mid, max);
